source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StackLayout_Example', :exclusive => true do
  pod "StackLayout", :path => "../"
end

target 'StackLayout_Tests', :exclusive => true do
  pod "StackLayout", :path => "../"

  
end
